{
 "title": "Enterprise Edge node monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Replicas Unavailable",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{deployment=~\"ent.*\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (image_id) (kube_pod_container_info)",
     "legendFormat": "{{image_id}}"
    }
   ]
  },
  {
   "title": "Component's CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod_name=~\"ent.*\"}[1m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Component's network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod_name=~\"ent.*\"}[1m])) by (pod_name)",
     "legendFormat": "<- {{pod_name}}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{pod_name=~\"ent.*\"}[1m])) by (pod_name)",
     "legendFormat": "-> {{pod_name}}"
    }
   ]
  },
  {
   "title": "Component's memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"ent.*\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Successful Request count - enterprise-smpp-server (Sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time ( {app=\"enterprise-smpp-server\"} |= \"SMID\" [1m])"
    }
   ]
  },
  {
   "title": "Failed Request count - enterprise-smpp-server (Sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time ( {app=\"enterprise-smpp-server\"} |= \"FMID\" [1m])"
    }
   ]
  },
  {
   "title": "Bind Failure Count - enterprise-smpp-server (Sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time ( {app=\"enterprise-smpp-server\"} |= \"BFID\" [1m])"
    }
   ]
  }
 ]
}